name: exponea_example
description: Demonstrates how to use the exponea plugin.
version: 2.3.0+1
publish_to: 'none'

environment:
  sdk: ^3.3.0
  flutter: ^3.19.0

dependencies:
  flutter:
    sdk: flutter

  exponea:
    path: ../

  shared_preferences: 2.1.1
  app_links: ^6.3.3

dev_dependencies:
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
