name: exponea_example
description: Demonstrates how to use the exponea plugin.
version: 1.4.2+1
publish_to: 'none'

environment:
  sdk: ^2.16.0
  flutter: ^2.10.0

dependencies:
  flutter:
    sdk: flutter

  exponea:
    path: ../

  shared_preferences: 2.0.13
  uni_links: 0.5.1

dev_dependencies:
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
