name: exponea
description: >-
  A full featured wrapper for Exponea SDK that supports Android and iOS.
version: 1.6.0
homepage: https://exponea.com
repository: https://github.com/exponea/exponea-flutter-sdk

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.7.0
  plugin_platform_interface: ^2.1.2
  file: ^6.1.4
  webview_flutter: ^4.0.7

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.exponea
        pluginClass: ExponeaPlugin
      ios:
        pluginClass: ExponeaPlugin

false_secrets:
 - /example/android/app/google-services.json
